Repository goorm-6zo/back, pull requests merged in 2025-03, with the labels that each got.

#23 관리자 QR 도메인 예외처리 추가 및 테스트 수정
  src/main/java/goorm/back/zo6/admin/application/QRCodeServiceImpl.java
  src/main/java/goorm/back/zo6/admin/domain/IdExistenceDao.java
  src/main/java/goorm/back/zo6/admin/infrastructure/ConferenceIdExistenceDao.java
  src/main/java/goorm/back/zo6/admin/infrastructure/SessionIdExistenceDao.java
  src/main/java/goorm/back/zo6/admin/presentation/QRCodeController.java
  src/main/java/goorm/back/zo6/common/exception/ErrorCode.java
  src/test/java/goorm/back/zo6/admin/application/QRCodeServiceImplTest.java
  src/test/java/goorm/back/zo6/admin/presentation/QRCodeControllerTest.java
Labels: ✨ feat, 💡test

#26 컨퍼런스,세션,예매 기능 구현
  src/main/java/goorm/back/zo6/conference/application/ConferenceDetailResponse.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceMapper.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceQueryService.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceQueryServiceImpl.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceResponse.java
  src/main/java/goorm/back/zo6/conference/application/SessionResponse.java
  src/main/java/goorm/back/zo6/conference/domain/Conference.java
  src/main/java/goorm/back/zo6/conference/domain/ConferenceRepository.java
  src/main/java/goorm/back/zo6/conference/domain/Session.java
  src/main/java/goorm/back/zo6/conference/domain/SessionRepository.java
  src/main/java/goorm/back/zo6/conference/infrastructure/ConferenceJpaRepository.java
  src/main/java/goorm/back/zo6/conference/infrastructure/ConferenceRepositoryImpl.java
  src/main/java/goorm/back/zo6/conference/infrastructure/SessionJpaRepository.java
  src/main/java/goorm/back/zo6/conference/infrastructure/SessionRepositoryImpl.java
  src/main/java/goorm/back/zo6/conference/presentation/ConferenceController.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationRequest.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationResponse.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationService.java
  src/main/java/goorm/back/zo6/reservation/domain/Reservation.java
  src/main/java/goorm/back/zo6/reservation/domain/ReservationRepository.java
  src/main/java/goorm/back/zo6/reservation/domain/ReservationSession.java
  src/main/java/goorm/back/zo6/reservation/infrastructure/ReservationJpaRepository.java
  src/main/java/goorm/back/zo6/reservation/infrastructure/ReservationRepositoryImpl.java
  src/main/java/goorm/back/zo6/reservation/presnetation/ReservationController.java
  src/main/resources/Zo6Application.yml
  src/test/java/goorm/back/zo6/admin/presentation/QRCodeControllerTest.java
Labels: ✨ feat

#36 QR 도메인 리팩토링 및 RestDocs 설정 추가
  build.gradle
  src/docs/asciidoc/qr-code.adoc
  src/main/java/goorm/back/zo6/common/exception/ErrorCode.java
  src/main/java/goorm/back/zo6/conference/domain/Conference.java
  src/main/java/goorm/back/zo6/conference/domain/Session.java
  src/main/java/goorm/back/zo6/qr/application/QRCodeResponse.java
  src/main/java/goorm/back/zo6/qr/application/QRCodeService.java
  src/main/java/goorm/back/zo6/qr/application/QRCodeServiceImpl.java
  src/main/java/goorm/back/zo6/qr/application/QRContentBuilder.java
  src/main/java/goorm/back/zo6/qr/domain/IdExistenceDao.java
  src/main/java/goorm/back/zo6/qr/domain/QRCodeGenerator.java
  src/main/java/goorm/back/zo6/qr/infrastructure/ConferenceIdExistenceDao.java
  src/main/java/goorm/back/zo6/qr/infrastructure/QRCodeGeneratorImpl.java
  src/main/java/goorm/back/zo6/qr/infrastructure/SessionIdExistenceDao.java
  src/main/java/goorm/back/zo6/qr/presentation/QRCodeController.java
  src/main/resources/Zo6Application.yml
  src/main/resources/static/docs/qr-code.html
  src/test/java/goorm/back/zo6/config/RestDocsConfiguration.java
  src/test/java/goorm/back/zo6/fixture/ConferenceFixture.java
  src/test/java/goorm/back/zo6/fixture/SessionFixture.java
  src/test/java/goorm/back/zo6/fixture/UserFixture.java
  src/test/java/goorm/back/zo6/qr/application/QRCodeServiceImplTest.java
  src/test/java/goorm/back/zo6/qr/infrastructure/QRCodeGeneratorImplTest.java
  src/test/java/goorm/back/zo6/qr/presentation/QRCodeControllerTest.java
Labels: 🎨refactor, 💡test, ⚙ build

#38 컨퍼런스,세션,예매 테스트 코드 작성
  src/main/java/goorm/back/zo6/common/exception/GlobalExceptionHandler.java
  src/main/java/goorm/back/zo6/conference/domain/Conference.java
  src/main/java/goorm/back/zo6/conference/domain/Session.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationResponse.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationService.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationServiceImpl.java
  src/main/java/goorm/back/zo6/reservation/domain/Reservation.java
  src/main/java/goorm/back/zo6/reservation/domain/ReservationRepository.java
  src/main/java/goorm/back/zo6/reservation/infrastructure/ReservationJpaRepository.java
  src/main/java/goorm/back/zo6/reservation/infrastructure/ReservationRepositoryImpl.java
  src/main/java/goorm/back/zo6/reservation/presnetation/ReservationController.java
  src/test/java/goorm/back/zo6/conference/application/ConferenceQueryServiceImplTest.java
  src/test/java/goorm/back/zo6/conference/presentation/ConferenceControllerTest.java
  src/test/java/goorm/back/zo6/fixture/SessionFixture.java
  src/test/java/goorm/back/zo6/fixture/UserFixture.java
  src/test/java/goorm/back/zo6/reservation/application/ReservationServiceImplTest.java
  src/test/java/goorm/back/zo6/reservation/presentation/ReservationControllerTest.java
Labels: 🎨refactor, 💡test

#43 SwaggerConfig 수정
  src/main/java/goorm/back/zo6/common/config/SwaggerConfig.java
Labels: 🔨fix

#45 Swagger Config 수정
  src/main/java/goorm/back/zo6/common/config/SwaggerConfig.java
Labels: 🔨fix

#48 cd 원상 복귀
  src/main/java/goorm/back/zo6/common/config/SwaggerConfig.java
Labels: 🎨refactor

#50 cors 에러 해결
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
Labels: 🔨fix

#53 cors 프론트 뚫기
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
Labels: 🔨fix

#58 다른 도메인에 쿠키 허용
  src/main/java/goorm/back/zo6/auth/util/CookieUtil.java
Labels: 🔨fix

#63 QR 오타 수정
  src/main/java/goorm/back/zo6/qr/application/QRContentBuilder.java
Labels: 🎨refactor

#67 얼굴 인증 후 참석 이벤트 발행 기능 추가
  build.gradle
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/auth/filter/JwtAuthFilter.java
  src/main/java/goorm/back/zo6/auth/util/CookieUtil.java
  src/main/java/goorm/back/zo6/auth/util/JwtUtil.java
  src/main/java/goorm/back/zo6/common/config/RedisConfig.java
  src/main/java/goorm/back/zo6/common/config/SwaggerConfig.java
  src/main/java/goorm/back/zo6/common/event/Event.java
  src/main/java/goorm/back/zo6/common/event/EventStoreHandler.java
  src/main/java/goorm/back/zo6/common/event/Events.java
  src/main/java/goorm/back/zo6/common/event/EventsConfiguration.java
  src/main/java/goorm/back/zo6/common/exception/ErrorCode.java
  src/main/java/goorm/back/zo6/eventstore/api/EventEntry.java
  src/main/java/goorm/back/zo6/eventstore/api/EventStore.java
  src/main/java/goorm/back/zo6/eventstore/infrastructure/JpqlEventStore.java
  src/main/java/goorm/back/zo6/eventstore/presentation/EventApi.java
  src/main/java/goorm/back/zo6/face/application/FaceManagementService.java
  src/main/java/goorm/back/zo6/face/application/FaceRecognitionService.java
  src/main/java/goorm/back/zo6/face/application/RekognitionService.java
  src/main/java/goorm/back/zo6/face/config/AwsConfig.java
  src/main/java/goorm/back/zo6/face/domain/Face.java
  src/main/java/goorm/back/zo6/face/dto/request/ParticipationRequest.java
  src/main/java/goorm/back/zo6/face/dto/response/FaceResponse.java
  src/main/java/goorm/back/zo6/face/infrastructure/RekognitionApiClient.java
  src/main/java/goorm/back/zo6/face/infrastructure/S3FaceClient.java
  src/main/java/goorm/back/zo6/face/infrastructure/event/AttendanceEvent.java
  src/main/java/goorm/back/zo6/face/presentation/FaceManagementController.java
  src/main/java/goorm/back/zo6/face/presentation/FaceRecognitionController.java
  src/main/java/goorm/back/zo6/face/presentation/RekognitionController.java
  src/main/java/goorm/back/zo6/sse/controller/AttendanceController.java
  src/main/java/goorm/back/zo6/sse/dto/AttendanceKeys.java
  src/main/java/goorm/back/zo6/sse/infrastructure/AttendanceEventHandler.java
  src/main/java/goorm/back/zo6/sse/infrastructure/AttendanceService.java
  src/main/java/goorm/back/zo6/sse/infrastructure/ClockHolder.java
  src/main/java/goorm/back/zo6/sse/infrastructure/SystemClockHolder.java
  src/main/java/goorm/back/zo6/sse/repository/EmitterRepository.java
  src/main/java/goorm/back/zo6/sse/repository/SseEmitterRepository.java
  src/main/java/goorm/back/zo6/sse/service/SseService.java
  src/main/java/goorm/back/zo6/user/application/UserService.java
  src/test/java/goorm/back/zo6/face/application/FaceManagementServiceTest.java
  src/test/java/goorm/back/zo6/face/application/FaceRecognitionServiceTest.java
  src/test/java/goorm/back/zo6/face/application/RekognitionServiceTest.java
  src/test/java/goorm/back/zo6/face/infrastructure/RekognitionApiClientTest.java
  src/test/java/goorm/back/zo6/face/infrastructure/S3FaceClientTest.java
  src/test/java/goorm/back/zo6/face/presentation/FaceRecognitionControllerTest.java
Labels: ✨ feat

#77 유저 도메인 생일 필드 제거
  src/main/java/goorm/back/zo6/user/application/UserService.java
  src/main/java/goorm/back/zo6/user/domain/User.java
  src/main/java/goorm/back/zo6/user/dto/request/SignUpRequest.java
  src/main/java/goorm/back/zo6/user/dto/response/UserResponse.java
  src/test/java/goorm/back/zo6/auth/application/AuthServiceTest.java
  src/test/java/goorm/back/zo6/auth/presentation/AuthControllerTest.java
  src/test/java/goorm/back/zo6/fixture/UserFixture.java
  src/test/java/goorm/back/zo6/user/application/UserServiceTest.java
  src/test/java/goorm/back/zo6/user/presentation/UserControllerTest.java
Labels: 🎨refactor

#81 Swagger 문서화 추가
  src/main/java/goorm/back/zo6/conference/presentation/ConferenceController.java
  src/main/java/goorm/back/zo6/conference/presentation/ConferenceCreateController.java
  src/main/java/goorm/back/zo6/conference/presentation/SessionCreateController.java
  src/main/java/goorm/back/zo6/conference/presentation/SessionUpdateController.java
  src/main/java/goorm/back/zo6/qr/presentation/QRCodeController.java
  src/main/java/goorm/back/zo6/reservation/presnetation/ReservationController.java
Labels: 📘 docs

#89 로그인 ResponseBody에 권한 응답 추가
  src/main/java/goorm/back/zo6/auth/application/AuthService.java
  src/main/java/goorm/back/zo6/auth/presentation/AuthController.java
  src/main/java/goorm/back/zo6/user/dto/response/LoginResponse.java
  src/test/java/goorm/back/zo6/auth/presentation/AuthControllerTest.java
Labels: ✨ feat

#84 관리자 컨퍼런스, 세션 목록 조회
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/auth/filter/JwtAuthFilter.java
  src/main/java/goorm/back/zo6/conference/presentation/ConferenceAdminController.java
  src/main/java/goorm/back/zo6/user/application/UserService.java
  src/main/java/goorm/back/zo6/user/presentation/AdminController.java
Labels: ✨ feat

#87 참여 행사 도메인 추가, 이벤트 기반 count 기능 수정
  src/main/java/goorm/back/zo6/attend/application/AttendService.java
  src/main/java/goorm/back/zo6/attend/domain/Attend.java
  src/main/java/goorm/back/zo6/attend/domain/AttendEvent.java
  src/main/java/goorm/back/zo6/attend/domain/AttendRepository.java
  src/main/java/goorm/back/zo6/attend/dto/AttendInfo.java
  src/main/java/goorm/back/zo6/attend/dto/AttendInfoResponse.java
  src/main/java/goorm/back/zo6/attend/dto/AttendKeys.java
  src/main/java/goorm/back/zo6/attend/dto/AttendResponse.java
  src/main/java/goorm/back/zo6/attend/dto/ConferenceInfoDto.java
  src/main/java/goorm/back/zo6/attend/dto/ConferenceSessionResponse.java
  src/main/java/goorm/back/zo6/attend/dto/SessionInfoDto.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendEventHandler.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendJpaRepository.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendRedisService.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendRepositoryImpl.java
  src/main/java/goorm/back/zo6/attend/presentation/AttendController.java
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/auth/domain/LoginUser.java
  src/main/java/goorm/back/zo6/common/exception/ErrorCode.java
  src/main/java/goorm/back/zo6/conference/presentation/ConferenceCreateController.java
  src/main/java/goorm/back/zo6/conference/presentation/SessionCreateController.java
  src/main/java/goorm/back/zo6/conference/presentation/SessionUpdateController.java
  src/main/java/goorm/back/zo6/face/application/FaceRecognitionService.java
  src/main/java/goorm/back/zo6/face/domain/FaceRepository.java
  src/main/java/goorm/back/zo6/face/infrastructure/FaceRepositoryImpl.java
  src/main/java/goorm/back/zo6/face/presentation/FaceRecognitionController.java
  src/main/java/goorm/back/zo6/reservation/domain/ReservationRepository.java
  src/main/java/goorm/back/zo6/reservation/infrastructure/ReservationJpaRepository.java
  src/main/java/goorm/back/zo6/reservation/infrastructure/ReservationRepositoryImpl.java
  src/main/java/goorm/back/zo6/sse/controller/SseController.java
  src/main/java/goorm/back/zo6/sse/infrastructure/AttendanceEventHandler.java
  src/main/java/goorm/back/zo6/sse/infrastructure/ClockHolder.java
  src/main/java/goorm/back/zo6/sse/infrastructure/SystemClockHolder.java
  src/main/java/goorm/back/zo6/sse/repository/SseEmitterRepository.java
  src/test/java/goorm/back/zo6/conference/application/ConferenceQueryServiceImplTest.java
  src/test/java/goorm/back/zo6/face/application/FaceRecognitionServiceTest.java
Labels: ✨ feat, 🎨refactor

#95 SMS 알림 기능 추가
  build.gradle
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/common/exception/ErrorCode.java
  src/main/java/goorm/back/zo6/notice/application/NoticeService.java
  src/main/java/goorm/back/zo6/notice/domain/Notice.java
  src/main/java/goorm/back/zo6/notice/domain/NoticeTarget.java
  src/main/java/goorm/back/zo6/notice/dto/NoticeRequest.java
  src/main/java/goorm/back/zo6/notice/infrastructure/NoticeRepository.java
  src/main/java/goorm/back/zo6/notice/infrastructure/ReservationAttendeePhoneDao.java
  src/main/java/goorm/back/zo6/notice/presntation/NoticeController.java
  src/test/java/goorm/back/zo6/notice/infrastructure/ReservationAttendeePhoneDaoTest.java
  src/test/java/goorm/back/zo6/notice/integration/NoticeIntegrationTest.java
Labels: ✨ feat

#85 예매 서비스 유저와 링크 될때 예매 아이디 값 제거
  src/main/java/goorm/back/zo6/common/exception/ErrorCode.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceCreateService.java
  src/main/java/goorm/back/zo6/conference/presentation/ConferenceController.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationService.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationServiceImpl.java
  src/main/java/goorm/back/zo6/reservation/domain/ReservationRepository.java
  src/main/java/goorm/back/zo6/reservation/infrastructure/ReservationJpaRepository.java
  src/main/java/goorm/back/zo6/reservation/infrastructure/ReservationRepositoryImpl.java
  src/main/java/goorm/back/zo6/reservation/presnetation/ReservationController.java
Labels: 🎨refactor

#93 사용자가 예매한 특정 컨퍼런스 상세 조회 추가
  src/main/java/goorm/back/zo6/conference/application/SessionDto.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationConferenceDetailResponse.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationService.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationServiceImpl.java
  src/main/java/goorm/back/zo6/reservation/domain/ReservationRepository.java
  src/main/java/goorm/back/zo6/reservation/infrastructure/ReservationJpaRepository.java
  src/main/java/goorm/back/zo6/reservation/infrastructure/ReservationRepositoryImpl.java
  src/main/java/goorm/back/zo6/reservation/presnetation/ReservationController.java
  src/test/java/goorm/back/zo6/reservation/presentation/ReservationControllerTest.java
Labels: ✨ feat, 🎨refactor

#102 로그인, 토큰, ResponseBody 수정
  src/main/java/goorm/back/zo6/auth/application/AuthService.java
  src/main/java/goorm/back/zo6/user/dto/response/LoginResponse.java
  src/main/java/goorm/back/zo6/user/dto/response/UserResponse.java
  src/test/java/goorm/back/zo6/user/presentation/UserControllerTest.java
Labels: 🎨refactor

#103 예매,컨퍼런스 테스트 코드 작성, 예매 유저 링크 api 유저 Id 값 제거
  src/main/java/goorm/back/zo6/reservation/application/ReservationRequest.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationService.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationServiceImpl.java
  src/main/java/goorm/back/zo6/reservation/presnetation/ReservationController.java
  src/main/java/goorm/back/zo6/user/domain/UserRepository.java
  src/main/java/goorm/back/zo6/user/infrastructure/UserJpaRepository.java
  src/main/java/goorm/back/zo6/user/infrastructure/UserRepositoryImpl.java
  src/test/java/goorm/back/zo6/conference/application/ConferenceQueryServiceImplTest.java
  src/test/java/goorm/back/zo6/conference/presentation/ConferenceControllerTest.java
  src/test/java/goorm/back/zo6/fixture/ReservationFixture.java
  src/test/java/goorm/back/zo6/fixture/SessionFixture.java
  src/test/java/goorm/back/zo6/reservation/application/ReservationServiceImplTest.java
  src/test/java/goorm/back/zo6/reservation/presentation/ReservationControllerTest.java
Labels: 🔨fix, 💡test

#105 Attend, Sse 도메인 테스트 코드 작성
  src/main/java/goorm/back/zo6/attend/application/AttendService.java
  src/main/java/goorm/back/zo6/attend/dto/ConferenceSessionResponse.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendRedisService.java
  src/main/java/goorm/back/zo6/attend/presentation/AttendController.java
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/auth/domain/LoginUser.java
  src/main/java/goorm/back/zo6/auth/filter/JwtAuthFilter.java
  src/main/java/goorm/back/zo6/auth/presentation/AuthController.java
  src/main/java/goorm/back/zo6/common/exception/ErrorCode.java
  src/main/java/goorm/back/zo6/face/presentation/FaceRecognitionController.java
  src/main/java/goorm/back/zo6/sse/application/SseService.java
  src/main/java/goorm/back/zo6/sse/infrastructure/EmitterRepository.java
  src/main/java/goorm/back/zo6/sse/infrastructure/SseEmitterRepository.java
  src/main/java/goorm/back/zo6/sse/presentation/SseController.java
  src/main/java/goorm/back/zo6/user/domain/User.java
  src/main/java/goorm/back/zo6/user/dto/response/UserResponse.java
  src/main/java/goorm/back/zo6/user/presentation/UserController.java
  src/test/java/goorm/back/zo6/attend/application/AttendServiceTest.java
  src/test/java/goorm/back/zo6/attend/infrastructure/AttendRedisServiceTest.java
  src/test/java/goorm/back/zo6/attend/presentation/AttendControllerTest.java
  src/test/java/goorm/back/zo6/auth/application/AuthServiceTest.java
  src/test/java/goorm/back/zo6/reservation/application/ReservationServiceImplTest.java
  src/test/java/goorm/back/zo6/sse/application/SseServiceTest.java
  src/test/java/goorm/back/zo6/sse/presentation/SseControllerTest.java
  src/test/java/goorm/back/zo6/user/application/UserServiceTest.java
Labels: 💡test

#107 jacoco 테스트 커버리지 추가
  build.gradle
  src/test/java/goorm/back/zo6/face/presentation/FaceRecognitionControllerTest.java
Labels: ✨ feat

#110 회원가입, 로그인 유효성 검사 추가
  src/main/java/goorm/back/zo6/attend/domain/Attend.java
  src/main/java/goorm/back/zo6/auth/application/AuthService.java
  src/main/java/goorm/back/zo6/auth/dto/request/LoginRequest.java
  src/main/java/goorm/back/zo6/auth/dto/response/LoginResponse.java
  src/main/java/goorm/back/zo6/auth/presentation/AuthController.java
  src/main/java/goorm/back/zo6/user/dto/request/LoginRequest.java
  src/main/java/goorm/back/zo6/user/dto/request/SignUpRequest.java
  src/main/java/goorm/back/zo6/user/presentation/UserController.java
  src/test/java/goorm/back/zo6/auth/application/AuthServiceTest.java
  src/test/java/goorm/back/zo6/auth/presentation/AuthControllerTest.java
  src/test/java/goorm/back/zo6/user/application/UserServiceTest.java
  src/test/java/goorm/back/zo6/user/presentation/UserControllerTest.java
Labels: 🎨refactor, 💡test

#111 세션 필드 추가
  src/main/java/goorm/back/zo6/attend/application/AttendService.java
  src/main/java/goorm/back/zo6/attend/dto/SessionInfoDto.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendJpaRepository.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceMapper.java
  src/main/java/goorm/back/zo6/conference/application/SessionCreateRequest.java
  src/main/java/goorm/back/zo6/conference/application/SessionCreateServiceImpl.java
  src/main/java/goorm/back/zo6/conference/application/SessionDto.java
  src/main/java/goorm/back/zo6/conference/application/SessionResponse.java
  src/main/java/goorm/back/zo6/conference/application/SessionService.java
  src/main/java/goorm/back/zo6/conference/application/SessionServiceImpl.java
  src/main/java/goorm/back/zo6/conference/application/SessionUpdateRequest.java
  src/main/java/goorm/back/zo6/conference/domain/Session.java
  src/main/java/goorm/back/zo6/conference/domain/SessionRepository.java
  src/main/java/goorm/back/zo6/conference/infrastructure/SessionJpaRepository.java
  src/main/java/goorm/back/zo6/conference/infrastructure/SessionRepositoryImpl.java
  src/main/java/goorm/back/zo6/conference/presentation/SessionUpdateController.java
  src/test/java/goorm/back/zo6/attend/application/AttendServiceTest.java
  src/test/java/goorm/back/zo6/attend/presentation/AttendControllerTest.java
  src/test/java/goorm/back/zo6/conference/application/ConferenceQueryServiceImplTest.java
  src/test/java/goorm/back/zo6/conference/presentation/ConferenceControllerTest.java
  src/test/java/goorm/back/zo6/fixture/SessionFixture.java
Labels: 🔨fix, ✨ feat

#115 세션 활성화 / 비활성화 api 추가
  src/main/java/goorm/back/zo6/conference/application/ConferenceQueryService.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceQueryServiceImpl.java
  src/main/java/goorm/back/zo6/conference/domain/Session.java
  src/main/java/goorm/back/zo6/conference/domain/SessionRepository.java
  src/main/java/goorm/back/zo6/conference/infrastructure/SessionJpaRepository.java
  src/main/java/goorm/back/zo6/conference/infrastructure/SessionRepositoryImpl.java
  src/main/java/goorm/back/zo6/conference/presentation/ConferenceAdminController.java
Labels: ✨ feat

#118 세션 수정 api 리팩터링
  src/main/java/goorm/back/zo6/conference/application/SessionService.java
  src/main/java/goorm/back/zo6/conference/application/SessionServiceImpl.java
  src/main/java/goorm/back/zo6/conference/application/SessionUpdateRequest.java
  src/main/java/goorm/back/zo6/conference/domain/Session.java
  src/main/java/goorm/back/zo6/conference/presentation/ConferenceAdminController.java
  src/main/java/goorm/back/zo6/conference/presentation/SessionUpdateController.java
Labels: 🎨refactor

#120 컨퍼런스,세션 이미지 s3 Url 필드 추가, 세션 발표자, 발표자 소속 필드 추가, 컨퍼런스 활성화 상태 필드 추가
  src/main/java/goorm/back/zo6/attend/application/AttendService.java
  src/main/java/goorm/back/zo6/attend/dto/ConferenceInfoDto.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendJpaRepository.java
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceCreateRequest.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceCreateServiceImpl.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceDetailResponse.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceMapper.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceResponse.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceSimpleResponse.java
  src/main/java/goorm/back/zo6/conference/application/SessionCreateRequest.java
  src/main/java/goorm/back/zo6/conference/application/SessionCreateServiceImpl.java
  src/main/java/goorm/back/zo6/conference/application/SessionDto.java
  src/main/java/goorm/back/zo6/conference/application/SessionResponse.java
  src/main/java/goorm/back/zo6/conference/application/SessionServiceImpl.java
  src/main/java/goorm/back/zo6/conference/application/SessionUpdateRequest.java
  src/main/java/goorm/back/zo6/conference/domain/Conference.java
  src/main/java/goorm/back/zo6/conference/domain/Session.java
  src/main/java/goorm/back/zo6/conference/domain/SessionRepository.java
  src/main/java/goorm/back/zo6/conference/infrastructure/S3FileService.java
  src/main/java/goorm/back/zo6/conference/infrastructure/SessionJpaRepository.java
  src/main/java/goorm/back/zo6/conference/infrastructure/SessionRepositoryImpl.java
  src/main/java/goorm/back/zo6/conference/presentation/ConferenceImageController.java
  src/main/java/goorm/back/zo6/face/config/AwsConfig.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationConferenceDetailResponse.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationResponse.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationServiceImpl.java
  src/test/java/goorm/back/zo6/attend/application/AttendServiceTest.java
  src/test/java/goorm/back/zo6/attend/presentation/AttendControllerTest.java
  src/test/java/goorm/back/zo6/conference/application/ConferenceQueryServiceImplTest.java
  src/test/java/goorm/back/zo6/conference/presentation/ConferenceControllerTest.java
  src/test/java/goorm/back/zo6/fixture/ConferenceFixture.java
  src/test/java/goorm/back/zo6/fixture/SessionFixture.java
  src/test/java/goorm/back/zo6/reservation/application/ReservationServiceImplTest.java
Labels: 🔨fix, ✨ feat

#123 이미지 url 잘못 들어간 부분 수정
  src/main/java/goorm/back/zo6/reservation/application/ReservationResponse.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationServiceImpl.java
Labels: 🔨fix

#126 세션, 컨퍼런스 시작시간 종료시간 필드 추가 -> 그에 맞춰서 기존 코드, 테스트 코드 수정
  src/main/java/goorm/back/zo6/attend/application/AttendService.java
  src/main/java/goorm/back/zo6/attend/dto/ConferenceInfoDto.java
  src/main/java/goorm/back/zo6/attend/dto/SessionInfoDto.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendJpaRepository.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceCreateRequest.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceCreateServiceImpl.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceDetailResponse.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceMapper.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceResponse.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceSimpleResponse.java
  src/main/java/goorm/back/zo6/conference/application/SessionCreateRequest.java
  src/main/java/goorm/back/zo6/conference/application/SessionCreateServiceImpl.java
  src/main/java/goorm/back/zo6/conference/application/SessionDto.java
  src/main/java/goorm/back/zo6/conference/application/SessionResponse.java
  src/main/java/goorm/back/zo6/conference/application/SessionServiceImpl.java
  src/main/java/goorm/back/zo6/conference/domain/Conference.java
  src/main/java/goorm/back/zo6/conference/domain/Session.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationConferenceDetailResponse.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationResponse.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationServiceImpl.java
  src/test/java/goorm/back/zo6/attend/application/AttendServiceTest.java
  src/test/java/goorm/back/zo6/attend/presentation/AttendControllerTest.java
  src/test/java/goorm/back/zo6/conference/application/ConferenceQueryServiceImplTest.java
  src/test/java/goorm/back/zo6/conference/presentation/ConferenceControllerTest.java
  src/test/java/goorm/back/zo6/fixture/ConferenceFixture.java
  src/test/java/goorm/back/zo6/fixture/SessionFixture.java
Labels: 🔨fix, ✨ feat

#122 참석자 플로우 비동기 처리
  src/main/java/goorm/back/zo6/attend/application/AttendService.java
  src/main/java/goorm/back/zo6/attend/dto/SessionInfoDto.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendEventHandler.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendJpaRepository.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendRedisService.java
  src/main/java/goorm/back/zo6/common/config/AsyncConfig.java
  src/main/java/goorm/back/zo6/common/config/AwsConfig.java
  src/main/java/goorm/back/zo6/face/application/FaceRecognitionService.java
  src/main/java/goorm/back/zo6/sse/presentation/SseController.java
  src/test/java/goorm/back/zo6/attend/application/AttendServiceTest.java
  src/test/java/goorm/back/zo6/attend/infrastructure/AttendRedisServiceTest.java
  src/test/java/goorm/back/zo6/attend/presentation/AttendControllerTest.java
  src/test/java/goorm/back/zo6/test/CustomTuple.java
  src/test/java/goorm/back/zo6/test/FaceAuthAsyncTest.java
  src/test/java/goorm/back/zo6/test/FaceAuthNoAsyncTest.java
  src/test/java/goorm/back/zo6/test/TestProcessCore.java
Labels: 🔨fix, 🎨refactor

#128 관리자 컨퍼런스 활성화, 비활성화 기능 구현
  src/main/java/goorm/back/zo6/conference/application/ConferenceQueryService.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceQueryServiceImpl.java
  src/main/java/goorm/back/zo6/conference/domain/Conference.java
  src/main/java/goorm/back/zo6/conference/presentation/ConferenceAdminController.java
  src/main/java/goorm/back/zo6/user/presentation/AdminController.java
Labels: ✨ feat

#131 컨퍼런스 관리자 기능 테스트 작성
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/conference/presentation/ConferenceAdminController.java
  src/test/java/goorm/back/zo6/conference/presentation/ConferenceAdminControllerTest.java
  src/test/java/goorm/back/zo6/fixture/AdminFixture.java
Labels: 🎨refactor, 💡test

#133 컨퍼런스 area 필드 추가 -> 다시 제거.. , 컨퍼런스 조회 시간 순 조회로 변경
  src/main/java/goorm/back/zo6/attend/application/AttendService.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceMapper.java
  src/main/java/goorm/back/zo6/conference/application/ConferenceQueryServiceImpl.java
  src/main/java/goorm/back/zo6/conference/application/SessionDto.java
  src/main/java/goorm/back/zo6/conference/domain/Conference.java
  src/main/java/goorm/back/zo6/conference/domain/ConferenceRepository.java
  src/main/java/goorm/back/zo6/conference/infrastructure/ConferenceJpaRepository.java
  src/main/java/goorm/back/zo6/conference/presentation/ConferenceController.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationConferenceDetailResponse.java
  src/main/java/goorm/back/zo6/reservation/application/ReservationServiceImpl.java
  src/test/java/goorm/back/zo6/attend/application/AttendServiceTest.java
  src/test/java/goorm/back/zo6/conference/presentation/ConferenceAdminControllerTest.java
  src/test/java/goorm/back/zo6/conference/presentation/ConferenceControllerTest.java
  src/test/java/goorm/back/zo6/fixture/ConferenceFixture.java
  src/test/java/goorm/back/zo6/fixture/ReservationFixture.java
  src/test/java/goorm/back/zo6/reservation/application/ReservationServiceImplTest.java
  src/test/java/goorm/back/zo6/reservation/presentation/ReservationControllerTest.java
Labels: 🔨fix, ✨ feat, 🎨refactor

#134 face, auth, user 리팩토링
  src/main/java/goorm/back/zo6/auth/application/AuthService.java
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/auth/domain/LoginUser.java
  src/main/java/goorm/back/zo6/auth/filter/JwtAuthFilter.java
  src/main/java/goorm/back/zo6/auth/presentation/AuthController.java
  src/main/java/goorm/back/zo6/auth/util/JwtUtil.java
  src/main/java/goorm/back/zo6/common/exception/ErrorCode.java
  src/main/java/goorm/back/zo6/face/application/FaceRecognitionService.java
  src/main/java/goorm/back/zo6/face/dto/response/FaceAuthResultResponse.java
  src/main/java/goorm/back/zo6/face/dto/response/FaceMatchingResponse.java
  src/main/java/goorm/back/zo6/face/infrastructure/RekognitionApiClient.java
  src/main/java/goorm/back/zo6/face/presentation/FaceRecognitionController.java
  src/main/java/goorm/back/zo6/reservation/domain/ReservationRepository.java
  src/main/java/goorm/back/zo6/reservation/infrastructure/ReservationJpaRepository.java
  src/main/java/goorm/back/zo6/reservation/infrastructure/ReservationRepositoryImpl.java
  src/main/java/goorm/back/zo6/user/application/UserService.java
  src/main/java/goorm/back/zo6/user/domain/UserRepository.java
  src/main/java/goorm/back/zo6/user/infrastructure/UserJpaRepository.java
  src/main/java/goorm/back/zo6/user/infrastructure/UserRepositoryImpl.java
  src/main/java/goorm/back/zo6/user/presentation/UserController.java
  src/test/java/goorm/back/zo6/attend/presentation/AttendControllerTest.java
  src/test/java/goorm/back/zo6/auth/application/AuthServiceTest.java
  src/test/java/goorm/back/zo6/conference/presentation/ConferenceAdminControllerTest.java
  src/test/java/goorm/back/zo6/conference/presentation/ConferenceControllerTest.java
  src/test/java/goorm/back/zo6/face/application/FaceRecognitionServiceTest.java
  src/test/java/goorm/back/zo6/face/infrastructure/RekognitionApiClientTest.java
  src/test/java/goorm/back/zo6/face/presentation/FaceRecognitionControllerTest.java
  src/test/java/goorm/back/zo6/qr/presentation/QRCodeControllerTest.java
  src/test/java/goorm/back/zo6/reservation/presentation/ReservationControllerTest.java
  src/test/java/goorm/back/zo6/user/application/UserServiceTest.java
  src/test/java/goorm/back/zo6/user/presentation/UserControllerTest.java
Labels: 🎨refactor

#138 Attend, Redis, Face 도메인 수정
  src/main/java/goorm/back/zo6/attend/application/AttendService.java
  src/main/java/goorm/back/zo6/attend/domain/AttendRepository.java
  src/main/java/goorm/back/zo6/attend/dto/AttendInfo.java
  src/main/java/goorm/back/zo6/attend/dto/AttendInfoResponse.java
  src/main/java/goorm/back/zo6/attend/dto/AttendResponse.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendEventHandler.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendRedisService.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendRepositoryImpl.java
  src/main/java/goorm/back/zo6/attend/presentation/AttendController.java
  src/main/java/goorm/back/zo6/attend/presentation/RedisController.java
  src/main/java/goorm/back/zo6/face/application/FaceRecognitionService.java
  src/main/java/goorm/back/zo6/face/infrastructure/RekognitionApiClient.java
  src/main/java/goorm/back/zo6/face/presentation/FaceRecognitionController.java
  src/main/java/goorm/back/zo6/sse/application/SseService.java
  src/main/java/goorm/back/zo6/sse/presentation/SseController.java
  src/test/java/goorm/back/zo6/attend/application/AttendServiceTest.java
  src/test/java/goorm/back/zo6/attend/infrastructure/AttendRedisServiceTest.java
Labels: ✨ feat, 🎨refactor

#147 Sse 재연결시 이전 데이터 유지
  src/main/java/goorm/back/zo6/sse/application/SseService.java
Labels: 🔨fix

#152 Kakao OAuth2 로그인 추가
  build.gradle
  src/main/java/goorm/back/zo6/auth/application/AbstractOAuth2LoginSuccessHandler.java
  src/main/java/goorm/back/zo6/auth/application/KakaoOAuth2LoginSuccessHandler.java
  src/main/java/goorm/back/zo6/auth/application/OAuth2LoginSuccessHandlerFactory.java
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/user/application/KakaoOAuth2UserServiceImpl.java
  src/main/java/goorm/back/zo6/user/application/OAuth2UserServiceFactory.java
  src/test/java/goorm/back/zo6/face/presentation/FaceRecognitionControllerTest.java
Labels: ✨ feat, ⚙ build

#154 전화번호 본인 인증 기능 추가
  src/main/java/goorm/back/zo6/Zo6Application.java
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/common/config/RedisConfig.java
  src/main/java/goorm/back/zo6/common/exception/ErrorCode.java
  src/main/java/goorm/back/zo6/user/application/PhoneValidService.java
  src/main/java/goorm/back/zo6/user/application/UserService.java
  src/main/java/goorm/back/zo6/user/domain/User.java
  src/main/java/goorm/back/zo6/user/dto/request/PhoneRequest.java
  src/main/java/goorm/back/zo6/user/dto/request/PhoneValidRequest.java
  src/main/java/goorm/back/zo6/user/presentation/UserController.java
  src/test/java/goorm/back/zo6/user/application/PhoneValidServiceTest.java
  src/test/java/goorm/back/zo6/user/presentation/UserControllerTest.java
Labels: ✨ feat

#162 커스텀 로깅 추가, 배포 상황 discord 예외 알림 기능 추가
  build.gradle
  src/main/java/goorm/back/zo6/attend/application/AttendService.java
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/auth/util/JwtUtil.java
  src/main/java/goorm/back/zo6/common/config/AsyncConfig.java
  src/main/java/goorm/back/zo6/common/exception/ErrorCode.java
  src/main/java/goorm/back/zo6/common/log/CorrelationIdFilter.java
  src/main/java/goorm/back/zo6/common/log/ExcludeErrorFilter.java
  src/main/java/goorm/back/zo6/common/log/LogFilter.java
  src/main/java/goorm/back/zo6/common/log/ThrowableCallable.java
  src/main/java/goorm/back/zo6/common/log/ThrowableRunnable.java
  src/main/java/goorm/back/zo6/common/log/TimeLogAspect.java
  src/main/java/goorm/back/zo6/common/log/TimeLogPointCut.java
  src/main/java/goorm/back/zo6/common/log/TimeLogTemplate.java
  src/main/resources/logback-spring.xml
  src/test/java/goorm/back/zo6/face/presentation/FaceRecognitionControllerTest.java
Labels: ✨ feat

#167 누락된 테스트 코드 작성
  src/main/java/goorm/back/zo6/face/application/FaceRecognitionService.java
  src/main/java/goorm/back/zo6/face/domain/FaceRepository.java
  src/main/java/goorm/back/zo6/face/infrastructure/FaceRepositoryImpl.java
  src/main/resources/logback-spring.xml
  src/test/java/goorm/back/zo6/attend/application/AttendServiceTest.java
  src/test/java/goorm/back/zo6/attend/presentation/AttendControllerTest.java
  src/test/java/goorm/back/zo6/face/application/FaceRecognitionServiceTest.java
Labels: 🎨refactor, 💡test

#170 이메일 중복 검증 기능 추가
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/user/application/UserService.java
  src/main/java/goorm/back/zo6/user/dto/request/EmailRequest.java
  src/main/java/goorm/back/zo6/user/presentation/UserController.java
Labels: ✨ feat

#171 s3 이미지 값이 빈 값 ("") 일 때 s3에서 예외가 터져 조회가 불가 했던 부분 수정
  src/main/java/goorm/back/zo6/conference/application/shared/ConferenceMapper.java
  src/main/java/goorm/back/zo6/conference/domain/Session.java
  src/test/java/goorm/back/zo6/reservation/application/ReservationQueryServiceImplTest.java
Labels: 🔨fix

#175 도메인 명 수정
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/common/config/QueryDslConfig.java
Labels: 🔨fix

#187 프론트 리다이렉트 주소 추가
  src/main/java/goorm/back/zo6/auth/application/AbstractOAuth2LoginSuccessHandler.java
Labels: 🔨fix

#190 쿠키 프론트 도메인 주소 추가
  src/main/java/goorm/back/zo6/auth/util/CookieUtil.java
Labels: 🔨fix

#193 response 쿠키 추가
  src/main/java/goorm/back/zo6/auth/application/AbstractOAuth2LoginSuccessHandler.java
Labels: 🔨fix

#195 쿼리 파라미터 토큰 정보 제거
  src/main/java/goorm/back/zo6/auth/application/AbstractOAuth2LoginSuccessHandler.java
Labels: 🔨fix

#198 QueryDsl 적용
  build.gradle
  src/main/java/goorm/back/zo6/attend/application/AttendService.java
  src/main/java/goorm/back/zo6/attend/domain/AttendRepository.java
  src/main/java/goorm/back/zo6/attend/dto/AttendData.java
  src/main/java/goorm/back/zo6/attend/dto/AttendanceSummaryQuery.java
  src/main/java/goorm/back/zo6/attend/dto/ConferenceInfoResponse.java
  src/main/java/goorm/back/zo6/attend/dto/SessionInfo.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendJpaRepository.java
  src/main/java/goorm/back/zo6/attend/infrastructure/AttendRepositoryImpl.java
  src/main/java/goorm/back/zo6/attend/presentation/AttendController.java
  src/main/java/goorm/back/zo6/auth/application/AbstractOAuth2LoginSuccessHandler.java
  src/main/java/goorm/back/zo6/common/config/QueryDslConfig.java
  src/test/java/goorm/back/zo6/attend/application/AttendServiceTest.java
Labels: 🎨refactor

#197 유저 회원가입 시 임시 예매와 링크 하는 api 추가
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/common/exception/ErrorCode.java
  src/main/java/goorm/back/zo6/user/application/PhoneValidService.java
  src/main/java/goorm/back/zo6/user/application/UserService.java
  src/main/java/goorm/back/zo6/user/application/UserValidator.java
  src/main/java/goorm/back/zo6/user/presentation/UserController.java
Labels: ✨ feat

#199 id값 Long으로 수정
  src/main/java/goorm/back/zo6/notice/infrastructure/ReservationAttendeePhoneDao.java
Labels: 🔨fix

#215 last-count 값 비우기 기능 추가
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/sse/application/SseService.java
  src/main/java/goorm/back/zo6/sse/presentation/SseController.java
Labels: ✨ feat

#216 로깅 수정
  src/main/resources/logback-spring.xml
Labels: 🔨fix

#217 로깅 수정, sseService lastCount 비우기 기능 추가
  src/main/java/goorm/back/zo6/auth/config/SecurityConfig.java
  src/main/java/goorm/back/zo6/sse/application/SseService.java
  src/main/java/goorm/back/zo6/sse/presentation/SseController.java
  src/main/resources/logback-spring.xml
Labels: 🔨fix, ✨ feat

#220 컨퍼런스와 세션에 s3이미지 url이 겹쳐져 있던 버그 수정..
  src/main/java/goorm/back/zo6/conference/application/shared/ConferenceFactory.java
  src/main/java/goorm/back/zo6/conference/application/shared/SessionFactory.java
Labels: 🔨fix

#223 fix#218-reservation-image
  src/main/java/goorm/back/zo6/attend/application/AttendDtoConverter.java
  src/main/java/goorm/back/zo6/attend/application/AttendService.java
  src/main/java/goorm/back/zo6/conference/application/shared/ConferenceFactory.java
  src/main/java/goorm/back/zo6/conference/application/shared/SessionFactory.java
  src/main/java/goorm/back/zo6/conference/infrastructure/S3FileService.java
  src/test/java/goorm/back/zo6/attend/application/AttendServiceTest.java
  src/test/java/goorm/back/zo6/attend/presentation/AttendControllerTest.java
Labels: 🔨fix
